{
 "title": "Bank Ops · Módulo 3",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Solicitudes por segundo",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(bank_http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Latencia p95 de predicción",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(bank_http_duration_seconds_bucket{route=\"/predict\"}[1m])))"
    }
   ]
  },
  {
   "title": "Errores 5xx por segundo",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(bank_http_requests_total{status=~\"5..\"}[1m]))"
    }
   ]
  },
  {
   "title": "Modelo disponible",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "bank_model_ready" }
   ]
  },
  {
   "title": "Predicciones por clase",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by(class)(rate(bank_predictions_total[1m]))"
    }
   ]
  },
  {
   "title": "Disponibilidad del target",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "up{job=\"bank-api\"}"
    }
   ]
  }
 ]
}