flowchart LR
 N0["Detectar incidente"] --> N1
 N1["Identificar vigente"] --> N2
 N2["Seleccionar anterior"] --> N3
 N3["Cambiar puntero"] --> N4
 N4["Reiniciar servicio"] --> N5
 N5["Consultar versión HTTP"]